# -*- coding: utf-8 -*-
"""heart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152bkbwdFtqxMNACiVAV6QF-twbzN9ggC
"""

import numpy as np
import pandas as pd

import os
for dirname, _,filname in os.walk('/kaggle/input'):
    for filename in filname:
        print(os.path.join(dirname,filename))

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as st
# %matplotlib inline

sns.set_style('whitegrid')

import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('heart.csv')

print(df.shape)

df.head()

df.info()

df.dtypes

df.describe()

df.columns

df['target'].nunique()

df['target'].unique()

df['target'].value_counts()

"""univarient"""

f, ax=plt.subplots(figsize=(8,5))
ax=sns.countplot(x='target',data=df)

df.groupby('sex')['target'].value_counts()

f,ax=plt.subplots(figsize=(8,6))
ax=sns.countplot(x='sex',hue='target',data=df)

ax = sns.catplot(x='target',col='sex',data=df,kind='count',height=5,aspect=1,palette='Set1')
plt.legend()

f, ax=plt.subplots(figsize=(8,5))
ax=sns.countplot(x='target',hue='sex',data=df)

f,ax =plt.subplots(figsize=(8,6))
ax=sns.countplot(x='target',hue='sex',data=df,palette='Set1')

f,ax=plt.subplots(figsize=(8,5))
ax=sns.countplot(x='target',data=df,facecolor=(0,0,0,0),linewidth=5,edgecolor=sns.color_palette('dark',3))

f, ax=plt.subplots(figsize=(8,5))
ax=sns.countplot(x='target',hue='fbs',data=df)

f, ax=plt.subplots(figsize=(8,5))
ax=sns.countplot(x='target',hue='exang',data=df)

"""bivarient"""

correlation=df.corr()

correlation['target'].sort_values(ascending=False)

df['cp'].nunique()

df['cp'].unique()

df['cp'].value_counts()

f,ax=plt.subplots(figsize=(8,5))
ax=sns.countplot(x='cp',data=df,palette='Set2')

df.groupby('cp')['target'].value_counts()

f,ax=plt.subplots(figsize=(8,5))
ax=sns.countplot(x='cp',hue='target',data=df,palette='Set3')

ax=sns.catplot(x='target',col='cp',data=df,kind='count',height=10,aspect=1,palette='Set2')
plt.legend()

df['thalach'].nunique()

df['thalach'].unique()

f, ax=plt.subplots(figsize=(10,8))
x=df['thalach']
ax=sns.distplot(x,bins=10)

f,ax=plt.subplots(figsize=(10,6))
x=df['thalach']
x=pd.Series(x,name='thalach variable')
ax=sns.distplot(x,bins=10)

f,ax=plt.subplots(figsize=(10,6))
x=df['thalach']
x=pd.Series(x,name='thalach variable')
ax=sns.distplot(x,bins=10,vertical=True)

f,ax=plt.subplots(figsize=(10,6))
x=df['thalach']
x=pd.Series(x,name='thalach variable')
ax=sns.kdeplot(x)

f,ax=plt.subplots(figsize=(10,6))
x=df['thalach']
x=pd.Series(x,name='thalach variable')
ax=sns.kdeplot(x,shade=True,shade_lowest=False,color='r')

f,ax=plt.subplots(figsize=(10,6))
x=df['thalach']
ax = sns.distplot(x, kde=False, rug=True, bins=10)

f,ax=plt.subplots(figsize=(10,6))
sns.stripplot(x='target',y='thalach',data=df)

f,ax=plt.subplots(figsize=(10,6))
sns.stripplot(x='target',y='thalach',data=df,jitter=0.01)

f,ax=plt.subplots(figsize=(10,6))
sns.boxplot(x='target',y='thalach',data=df,palette='Set2')

plt.figure(figsize=(10,6))
plt.title('correlation heatmap of heart diseases')
a = sns.heatmap(correlation, square=True, annot=True, fmt='.2f', linecolor='white')
a.set_xticklabels(a.get_xticklabels(),rotation=90)
a.set_yticklabels(a.get_yticklabels(),rotation=30)

num_var=['age', 'trestbps', 'chol', 'thalach', 'oldpeak', 'target']
sns.pairplot(df[num_var],kind='scatter',diag_kind='hist')

df['age'].nunique()

df['age'].describe()

f,ax=plt.subplots(figsize=(10,6))
x=df['age']
ax=sns.distplot(x,bins=10)

f,ax=plt.subplots(figsize=(10,6))
ax=sns.stripplot(x='target',y='age',data=df)

f,ax=plt.subplots(figsize=(8,6))
ax=sns.boxplot(x='target',y='age',data=df,palette='Set2')

f,ax=plt.subplots(figsize=(10,8))
ax=sns.stripplot(x='target',y='trestbps',data=df)

f,ax=plt.subplots(figsize=(8,6))
ax=sns.regplot(x='age',y='trestbps',data=df)

f,ax=plt.subplots(figsize=(8,6))
ax=sns.scatterplot(x='age',y='chol',data=df,color='r')

f,ax=plt.subplots(figsize=(10,7))
ax=sns.regplot(x='age',y='chol',data=df)

f,ax=plt.subplots(figsize=(10,8))
ax=sns.scatterplot(x='chol',y='thalach',data=df)

f,ax=plt.subplots(figsize=(10,8))
ax=sns.regplot(x='chol',y='thalach',data=df)

df.isnull()

df.isnull().sum()

assert pd.notnull(df).all().all()

assert (df>=0).all().all()

df['age'].describe()

f,ax=plt.subplots(figsize=(10,7))
sns.boxplot(x='age',data=df)

df['trestbps'].describe()

f,ax=plt.subplots(figsize=(10,7))
ax=sns.boxplot(x='trestbps',data=df)

df['chol'].describe()

f,ax=plt.subplots(figsize=(10,7))
ax=sns.boxplot(x='chol',data=df)

df['thalach'].describe()

f,ax=plt.subplots(figsize=(10,7))
ax=sns.boxplot(x='thalach',data=df)

df['oldpeak'].describe()

f,ax=plt.subplots(figsize=(10,6))
ax=sns.boxplot(x='oldpeak',data=df)



