# -*- coding: utf-8 -*-
"""27-Feb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p5Ko-jDh63lRgCZ-3cRXDvRUH91UdC42
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

movies = pd.read_csv('Movie-Rating.csv')

movies

len(movies)

print(np.__version__)

print(pd.__version__)

movies.columns

movies.info()

movies.shape

movies.head()

movies.tail()

movies.columns

movies.columns=['film','Genre','Criticrating','Audiencerating','Budgetmillions','Year']

movies.columns

movies.head(1)

movies.describe()

movies.info()

movies.film = movies.film.astype('category')

movies. Genre = movies.Genre.astype('category')

movies.Year = movies.Year.astype('category')

movies.info()

movies.describe()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import warnings
warnings.filterwarnings('ignore')

j = sns.jointplot(data=movies,x='Criticrating',y='Audiencerating')

j = sns.jointplot(data=movies,x='Criticrating',y='Audiencerating', kind='hex')

j = sns.jointplot(data=movies,x='Criticrating',y='Audiencerating', kind='kde') # somnemore kind types check

m1 = sns.distplot(movies.Audiencerating) # distplot=distribution plot

m1 = sns.displot(movies.Audiencerating) # distplot=distribution plot

m2 = sns.distplot(movies.Criticrating) # distplot=distribution plot

sns.set_style('darkgrid') #whitegrid, dark, white, ticks

m2 = sns.distplot(movies.Criticrating) # distplot=distribution plot

sns.set_style('white')
m3 = sns.distplot(movies.Criticrating, bins=10) # distplot=distribution plot

sns.set_style('whitegrid')
m3 = plt.hist(movies.Criticrating, bins=15) # distplot=distribution plot

plt.hist(movies.Budgetmillions)

vis1 = sns.lmplot(data=movies, x='Criticrating', y='Audiencerating', fit_reg=False, hue='Genre')

vis1 = sns.lmplot(data=movies, x='Criticrating', y='Audiencerating', fit_reg=True, hue='Genre')















